In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

In [4]:
df=pd.read_excel("/content/drive/MyDrive/DA/ApexPlanet_DataAnalytics_Dataset.xlsx")

In [5]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

### Task 1: Data Understanding and Initial Exploration

First, let's get a concise summary of the DataFrame, including the data types of each column and the number of non-null values. Then, we will look at descriptive statistics for numerical columns.

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB
None

In [7]:
display(df.describe())

              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

### Missing Value Analysis

Let's calculate the percentage of missing values for each column to understand the extent of the data incompleteness.

In [8]:
missing_values = df.isnull().sum()
missing_percentage = (missing_values / len(df)) * 100

missing_info = pd.DataFrame({
    'Missing Count': missing_values,
    'Missing Percentage': missing_percentage
})

display(missing_info[missing_info['Missing Count'] > 0].sort_values(by='Missing Percentage', ascending=False))

      Missing Count  Missing Percentage
Age              20                 2.0
City             13                 1.3

### Handling Missing Values

Given the relatively small percentage of missing values in 'Age' and 'City', we will impute them. For 'Age', we'll use the median, and for 'City', we'll use the mode.

In [10]:
# Impute missing 'Age' values with the median
df['Age'] = df['Age'].fillna(df['Age'].median())

# Impute missing 'City' values with the mode
df['City'] = df['City'].fillna(df['City'].mode()[0])

# Verify that there are no more missing values
print('Missing values after imputation:')
display(df.isnull().sum())

Missing values after imputation:

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
dtype: int64

### Data Type Conversion

The 'Order_Date' column is currently an object type. Converting it to a datetime format will allow for time-based analysis.

In [11]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

print('Data types after conversion:')
display(df.info())

Data types after conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   datetime64[ns]
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            1000 non-null   float64
 5   Gender         1000 non-null   object
 6   City           1000 non-null   object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 93.9+ KB

None

### Duplicate Entry Handling

It's important to check for and remove any duplicate rows to ensure the integrity and accuracy of our analysis. Duplicates can skew statistics and lead to incorrect conclusions.

In [12]:
initial_rows = df.shape[0]
df.drop_duplicates(inplace=True)
final_rows = df.shape[0]

print(f"Initial number of rows: {initial_rows}")
print(f"Number of rows after removing duplicates: {final_rows}")
print(f"Number of duplicate rows removed: {initial_rows - final_rows}")

Initial number of rows: 1000
Number of rows after removing duplicates: 1000
Number of duplicate rows removed: 0

### Categorical Feature Analysis

Let's examine the unique values and their counts for key categorical columns to understand their distribution and identify any potential inconsistencies.

In [14]:
for column in ['Gender', 'City', 'Product', 'Category']:
    print(f"\nUnique values and their counts for '{column}':")
    display(df[column].value_counts())

Unique values and their counts for 'Gender':

Gender
Male      511
Female    489
Name: count, dtype: int64

Unique values and their counts for 'City':

City
Patna        148
Kolkata      133
Mumbai       131
Hyderabad    125
Delhi        125
Bengaluru    122
Gaya         117
Pune          99
Name: count, dtype: int64

Unique values and their counts for 'Product':

Product
Mobile    184
Book      178
Laptop    170
Chair     159
Shoes     156
Rice      153
Name: count, dtype: int64

Unique values and their counts for 'Category':

Category
Electronics    354
Education      178
Furniture      159
Fashion        156
Grocery        153
Name: count, dtype: int64

In [15]:
print(f"\nUnique values and their counts for 'Product':")
display(df['Product'].value_counts())

print(f"\nUnique values and their counts for 'Category':")
display(df['Category'].value_counts())

Unique values and their counts for 'Product':

Product
Mobile    184
Book      178
Laptop    170
Chair     159
Shoes     156
Rice      153
Name: count, dtype: int64

Unique values and their counts for 'Category':

Category
Electronics    354
Education      178
Furniture      159
Fashion        156
Grocery        153
Name: count, dtype: int64